### ISSUE TITLE
using microphones spearately

### ISSUE THREAD

**Issue by b7amine** [matrix-io/matrix-creator-malos#112]
Hello i'm running the odas sound tracking programm it's working great , now i'm trying to record the sound while the odas code is running which possible since I've got 8 mics , i'd like to know how I can configure one mic for recording and the other 7 for the odas sound tracking .I dont know yet how to work with the microphones separately and allocate each one for a task , make them perform different tasks simultaneously thank you so much.

**Comment by samreenislam** [comment]
Hello, your post has been addressed on the MATRIX Community [here](https://community.matrix.one/t/microphone-array-separately/2266/2?u=samreen). Please post your issue in one location going forward so as to avoid duplicate answers. Thanks!
