### ISSUE TITLE
Missing dep

### ISSUE THREAD

**Issue by buildog** [matrix-io/matrix-creator-malos#19]
At first install, I had to add 

`echo "deb http://packages.matrix.one/matrix-creator/ ./" | sudo tee --append /etc/apt/sources.list
 sudo apt-get install libzmq3 libzmq3-dev`

That's maybe worth adding this to the doc ? FYI I'm using resin.io to push the code to the Pi

**Comment by brianofrokk3r** [comment]
Thanks @buildog we're going to add it now, we also have these which we're migrating to:
https://matrix-io.github.io/matrix-documentation/

**Comment by brianofrokk3r** [comment]
@buildog updated `README.md` on master.

**Comment by brianofrokk3r** [comment]
@buildog if you have a resin.io deployment going let us know, would be cool to see it.

**Comment by buildog** [comment]
np, I'll share the process when ready ;-)
