### ISSUE TITLE
Move error messages from striings to protos

### ISSUE THREAD

**Issue by arhuaco** [matrix-io/matrix-creator-malos#21]
Here I'm talking about the error messages that MALOS returns on the error channel.
It's important to migrate before people start depending on error messages.

**Comment by arhuaco** [comment]
This is an urgent and important issue. We should fix it before using MALOS as a base for other binaries. The changes made here will propagate to MALOS-eye.

**Comment by brianofrokk3r** [comment]
@arhuaco is this resolved?

**Comment by arhuaco** [comment]
I think we're no longer doing this. We have strings in many places. We might want to standardize messages so they start with "ERROR" and "INFO", and tread the error channel as "stderr".
