### ISSUE TITLE
Camera initialization migrated to malos. Update documentation to reflect this.

### ISSUE THREAD

**Issue by brianofrokk3r** [matrix-io/matrix-creator-malos#22]
Update installation here.
https://github.com/matrix-io/matrix-documentation

**Comment by brianofrokk3r** [comment]
@arhuaco what steps change now?

**Comment by arhuaco** [comment]
No longer needed (done by matrix-creator-init -- uploading package now).

```
# Enable your camera on your Pi.
sudo raspi-config;
sudo reboot;
```

No longer needed, these run as services.

```
# currently needs to be run on every restart
sudo modprobe bcm2835-v4l2;
# before you run
malos_eye & malos 2>&1
```

I can send PR.

**Comment by brianofrokk3r** [comment]
@arhuaco perfect.

**Comment by arhuaco** [comment]
I couldn't create a branch in the doc repo. Here is a patch in the mean time.

[config-update.patch.gz](https://github.com/matrix-io/matrix-creator-malos/files/530155/config-update.patch.gz)

**Comment by arhuaco** [comment]
This is pending. The previous patch is easy to apply... Pinging so that we can close this issue.

**Comment by brianofrokk3r** [comment]
@arhuaco this is done -- I left reboot. Good to cleanup anyway.
