### ISSUE TITLE
Not works flag in Temperature calibration in test_humidity.js

### ISSUE THREAD

**Issue by kdpatino** [matrix-io/matrix-creator-malos#44]
If you change in test_humidity.js:

```
// Real current temperature [Celsius] for calibration 
hum_params_msg.current_temperature = 23
hum_params_msg.do_calibration = false
driverConfigProto.set_humidity(hum_params_msg)

```

Not works, still show the calibrated temperature 

{ humidity: 33.155372619628906,
  temperature: 22.544891357421875,
  temperature_raw: 35.45536422729492,
  temperature_is_calibrated: true }

**Comment by yoelrc88** [comment]
Checking this ..

**Comment by kdpatino** [comment]
Remove Flag to configure calibration now just  report raw and calibrated data
