### ISSUE TITLE
Create a library with ZMQ classes

### ISSUE THREAD

**Issue by arhuaco** [matrix-io/matrix-creator-malos#55]
Add a new ZMQ class to actually do PUSH (and not PUB).

```
  zmq::context_t context(1);
  zmq::socket_t publisher (context, ZMQ_PUSH);
  publisher.connect("tcp://127.0.0.1:22013");
```

We should have this as a library. It's being used in two places already.

**Comment by arhuaco** [comment]
Same for ZMQ_SUB.

**Comment by brianofrokk3r** [comment]
@arhuaco closed?

**Comment by arhuaco** [comment]
I'll create a library when we need to update MALOS-eye to the new version (the new one after the freeze).
