### ISSUE TITLE
Access to remaining sensors?

### ISSUE THREAD

**Issue by luisnomad** [matrix-io/matrix-creator-malos#60]
I'd like to see if there are plans to include access to the remaining sensors not covered by the current implementation:

- 3D Accelerometer
- 3D Gyroscope
- 3D Magnetometer

Looks like they have no ports we can connect to, like we do with temperature, the mics array, etc

**Comment by brianofrokk3r** [comment]
Hey @luisnomad 

You should be able to access those through the IMU sensor data. It should look something like this:

```
{ yaw: 136.6683349609375,
  pitch: 1.92928147315979,
  roll: -4.9146623611450195,
  accel_x: -0.0338134765625,
  accel_y: -0.08599853515625,
  accel_z: 1.0001220703125,
  gyro_x: 1.6748046875,
  gyro_y: -1.6448974609375,
  gyro_z: 0.76263427734375,
  mag_x: 0.22260001301765442,
  mag_y: 0.21000000834465027,
  mag_z: -0.07252000272274017 }
```

We also posted a release update here yesterday:
https://github.com/matrix-io/matrix-creator-malos/releases/tag/0.1-4.9
