### ISSUE TITLE
Python Examples are broken

### ISSUE THREAD

**Issue by erinxocon** [matrix-io/matrix-creator-malos#76]
It seems as if the protobuffers had changed a bit and the code hadn't been updated to reflect that.  It's also not super clear from the examples on how to use the protobuffs, expanded documentation would be great!

**Comment by erinxocon** [comment]
I've written PR #75 to help address some of these issues!

**Comment by samwel89** [comment]
Hi @erinxocon,

I have tested your PR but I still get some errors. Do I miss something? Or there must be some updates from Matrix Creator to be able to use your PR? However, I have also tested the original file "test_everloop.py" but I have this same error. Any idea?

Thank you in advance.

![image](https://user-images.githubusercontent.com/26720867/28132973-b9212206-673e-11e7-9f3d-30beb4615432.png)

**Comment by erinxocon** [comment]
huh interesting @samwel89, what version of python were you using?  I assume you have compiled the most up to date protobufs?

**Comment by samwel89** [comment]
I use python 2.7.9, and my protoc --version is `libprotoc 3.2.0`

**Comment by erinxocon** [comment]
@samwel89 I can take a look at it tomorrow!

**Comment by samwel89** [comment]
@erinxocon Okay, I will be waiting! Thank you in advance.

**Comment by samwel89** [comment]
Hello @erinxocon,
Any updates? Did you take a look?

**Comment by erinxocon** [comment]
@samwel89 did you happen to check the new release containing the official python updates along with the updated protodrivers?  It can be found [here](https://github.com/matrix-io/matrix-creator-malos/tree/master/src/python_test).  You should just be be able to fetch the new changes!  Can you check those out and let me know?

**Comment by samwel89** [comment]
Yes, I have just seen them after I texted you. However, I have tested "test_everloop.py" and I still get this error `ImportError: No module named matrix_io.proto.malos.V1` it looks like they didn't update the README.md to show how to import these new protodrivers. Any idea?

N.B: Before testing I have done: sudo apt-get update && sudo apt-get upgrade

**Comment by erinxocon** [comment]
@samwel89 I've got some time right now, let me see if I can replicate.  I'm gonna start with a fresh image and go from there.

**Comment by samwel89** [comment]
OK, cool! let me know your progress!

**Comment by hpsaturn** [comment]
@samwel89 please try upgrade all pip packages on your raspberryPi:
`sudo pip freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 sudo pip install -U`
and then install from requirements:
`sudo pip install -r requirements.txt`

**Comment by samwel89** [comment]
@hpsaturn yes, now it works! Thank you.
