### ISSUE TITLE
error test_doa.js

### ISSUE THREAD

**Issue by manzonif** [matrix-io/matrix-creator-malos#77]
Hi, I tried run test DOA but malos crash with the follow error:
terminate called after throwing an instance of 'std::bad_array_new_length'
  what():  std::bad_array_new_length.

Then I restarted malos manually and the I got error message from socket:
Message received: UV error: 1, Could not send update for MicArray_Alsa driver.

**Comment by lucasmoraisdev** [comment]
had you updated/upgrade your dependencies ?

**Comment by manzonif** [comment]
with the command : 
sudo apt-get update && sudo apt-get upgrade.

------------------------------------------------------------------
The following packages have been kept back:
   Libblas-dev libblas3 matrix-creator-malos

ok, solved with:  sudo apt-get --with-new-pkgs upgrade.
Thanks
