### ISSUE TITLE
Satisfying pre-requisites on a mac

### ISSUE THREAD

**Issue by Beeze** [matrix-io/matrix-creator-malos#98]
There are no instructions on how to do the commands on a mac, so I'm unable to get MALOS to work on my system.

**Comment by Beeze** [comment]
unless...... is this suppose to be done on the Pi?

**Comment by lucasmoraisdev** [comment]
Yes, please install on the Pi connected with the CREATOR board.

**Comment by Beeze** [comment]
Thanks.
